### PR TITLE
Module features to customize setup

### PR DESCRIPTION
**Pull request by misurellig**
Hi there

This PR to integrate a bunch of customizations required to setup Amazon OpenSearch domain in dev/test envs.

Addendum involves mainly:
  * Possibility to disable SAML authentication
  * Refer to an existing ACM cert (eg. catch-all cert) without creating a new one
  * Enlarge instance types to use
  * Add VPC and EBS config settings for OpenSearch domain

### CODE REVIEW

**Comment by dadimah** [comment]
@steveteuber @smlgbl Could you review the code. Waiting for VPC-based endpoint and option to disable the saml authentication.

**Comment by yatanasov** [comment]
@dadimah  - do you have a VPC OpenSearch module version ? :)

**Comment by AlexeyRaga** [comment]
Can this useful PR be merged now?

**Comment by skibinstein** [comment]
Hey, 

Happy New Year!
@steveteuber @smlgbl Could we merge this PR, please?

Thank you.

**Comment by steveteuber** [comment]
Hey, Happy New Year to you too! Sorry for the really late reply.
Today we will upgrade our OpenSearch cluster to v2.3 and after that I will merge all open PRs.

**Pull request merged**
